import Head from 'next/head';

export default function Layout({ children }) {
	return (
		<>
			<Head>
				<title>Pokedex</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='flex min-h-full flex-col justify-center py-12 px-8'>
				<div className='mx-auto w-full max-w-md'>
					<h2 className='mt-6 text-center text-3xl font-bold tracking-tight text-gray-900'>
						Hello, World!
					</h2>
					<p className='mt-2 text-center text-sm text-gray-600'>Subtitle</p>
				</div>

				{children}
			</main>
		</>
	);
}
